aeb_mux:
  ros__parameters:
    scan_topic: /scan
    odom_topic: /vesc/odom
    input_motor_speed_topic: /planner/motor/speed
    input_servo_position_topic: /planner/servo/position
    output_motor_speed_topic: /commands/motor/speed
    output_servo_position_topic: /commands/servo/position

    lidar_yaw_offset_deg: 90.0
    front_fov_deg: 70.0
    lidar_to_bumper_m: 0.10
    stop_clearance_m: 0.20
    slow_clearance_m: 0.75
    ttc_threshold_s: 0.45
    command_timeout_s: 0.35
    max_erpm: 8500.0
    servo_center: 0.5
